version: 2
workflows:
  version: 2
  build:
    jobs:
    - verify: 
        context: Production Credentials
jobs:
  verify:
    description: Explores contexts
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
      - run: echo ${FAKE_SECRET}
